/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'Dashboard': RouteRecordInfo<
      'Dashboard',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Documentations': RouteRecordInfo<
      'Documentations',
      '/documentation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Config': RouteRecordInfo<
      'Config',
      '/documentation/config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Hooks': RouteRecordInfo<
      'Hooks',
      '/hooks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'useKeyboardNavigation': RouteRecordInfo<
      'useKeyboardNavigation',
      '/hooks/use-keyboard-navigation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Components': RouteRecordInfo<
      'Components',
      '/ui-kit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Buttons': RouteRecordInfo<
      'Buttons',
      '/ui-kit/buttons',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Button': RouteRecordInfo<
      'Button',
      '/ui-kit/buttons/button',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'IconButton': RouteRecordInfo<
      'IconButton',
      '/ui-kit/buttons/icon-button',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Data': RouteRecordInfo<
      'Data',
      '/ui-kit/data',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Accordion': RouteRecordInfo<
      'Accordion',
      '/ui-kit/data/accordion',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Avatar': RouteRecordInfo<
      'Avatar',
      '/ui-kit/data/avatar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Divider': RouteRecordInfo<
      'Divider',
      '/ui-kit/data/divider',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Icon': RouteRecordInfo<
      'Icon',
      '/ui-kit/data/icon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Message': RouteRecordInfo<
      'Message',
      '/ui-kit/data/message',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Progress': RouteRecordInfo<
      'Progress',
      '/ui-kit/data/progress',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ScrollArea': RouteRecordInfo<
      'ScrollArea',
      '/ui-kit/data/scroll-area',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Skeleton': RouteRecordInfo<
      'Skeleton',
      '/ui-kit/data/skeleton',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Table': RouteRecordInfo<
      'Table',
      '/ui-kit/data/table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Tag': RouteRecordInfo<
      'Tag',
      '/ui-kit/data/tag',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Form': RouteRecordInfo<
      'Form',
      '/ui-kit/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Checkbox': RouteRecordInfo<
      'Checkbox',
      '/ui-kit/form/checkbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Group': RouteRecordInfo<
      'Group',
      '/ui-kit/form/group',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Input': RouteRecordInfo<
      'Input',
      '/ui-kit/form/input',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ListBox': RouteRecordInfo<
      'ListBox',
      '/ui-kit/form/listbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Radio': RouteRecordInfo<
      'Radio',
      '/ui-kit/form/radio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Select': RouteRecordInfo<
      'Select',
      '/ui-kit/form/select',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SelectButton': RouteRecordInfo<
      'SelectButton',
      '/ui-kit/form/select-button',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Switch': RouteRecordInfo<
      'Switch',
      '/ui-kit/form/switch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Textarea': RouteRecordInfo<
      'Textarea',
      '/ui-kit/form/textarea',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Navigation': RouteRecordInfo<
      'Navigation',
      '/ui-kit/navigation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Breadcrumbs': RouteRecordInfo<
      'Breadcrumbs',
      '/ui-kit/navigation/breadcrumbs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'Dashboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/documentation/index.vue': {
      routes:
        | 'Documentations'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/documentation/config/index.vue': {
      routes:
        | 'Config'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/hooks/index.vue': {
      routes:
        | 'Hooks'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/hooks/use-keyboard-navigation/index.vue': {
      routes:
        | 'useKeyboardNavigation'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/index.vue': {
      routes:
        | 'Components'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/buttons/index.vue': {
      routes:
        | 'Buttons'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/buttons/button/index.vue': {
      routes:
        | 'Button'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/buttons/icon-button/index.vue': {
      routes:
        | 'IconButton'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/data/index.vue': {
      routes:
        | 'Data'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/data/accordion/index.vue': {
      routes:
        | 'Accordion'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/data/avatar/index.vue': {
      routes:
        | 'Avatar'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/data/divider/index.vue': {
      routes:
        | 'Divider'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/data/icon/index.vue': {
      routes:
        | 'Icon'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/data/message/index.vue': {
      routes:
        | 'Message'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/data/progress/index.vue': {
      routes:
        | 'Progress'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/data/scroll-area/index.vue': {
      routes:
        | 'ScrollArea'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/data/skeleton/index.vue': {
      routes:
        | 'Skeleton'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/data/table/index.vue': {
      routes:
        | 'Table'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/data/tag/index.vue': {
      routes:
        | 'Tag'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/form/index.vue': {
      routes:
        | 'Form'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/form/checkbox/index.vue': {
      routes:
        | 'Checkbox'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/form/group/index.vue': {
      routes:
        | 'Group'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/form/input/index.vue': {
      routes:
        | 'Input'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/form/listbox/index.vue': {
      routes:
        | 'ListBox'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/form/radio/index.vue': {
      routes:
        | 'Radio'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/form/select/index.vue': {
      routes:
        | 'Select'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/form/select-button/index.vue': {
      routes:
        | 'SelectButton'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/form/switch/index.vue': {
      routes:
        | 'Switch'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/form/textarea/index.vue': {
      routes:
        | 'Textarea'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/navigation/index.vue': {
      routes:
        | 'Navigation'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-kit/navigation/breadcrumbs/index.vue': {
      routes:
        | 'Breadcrumbs'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
