// generated by @dotdev/theme — do not edit
var tokens = {
  "primitives": {
    "brand-50": "var(--color-indigo-50)",
    "brand-100": "var(--color-indigo-100)",
    "brand-200": "var(--color-indigo-200)",
    "brand-300": "var(--color-indigo-300)",
    "brand-400": "var(--color-indigo-400)",
    "brand-500": "var(--color-indigo-500)",
    "brand-600": "var(--color-indigo-600)",
    "brand-700": "var(--color-indigo-700)",
    "brand-800": "var(--color-indigo-800)",
    "brand-900": "var(--color-indigo-900)",
    "brand-950": "var(--color-indigo-950)",
    "neutral-50": "var(--color-shadow-grey-50)",
    "neutral-100": "var(--color-shadow-grey-100)",
    "neutral-200": "var(--color-shadow-grey-200)",
    "neutral-300": "var(--color-shadow-grey-300)",
    "neutral-400": "var(--color-shadow-grey-400)",
    "neutral-500": "var(--color-shadow-grey-500)",
    "neutral-600": "var(--color-shadow-grey-600)",
    "neutral-700": "var(--color-shadow-grey-700)",
    "neutral-800": "var(--color-shadow-grey-800)",
    "neutral-900": "var(--color-shadow-grey-900)",
    "neutral-950": "var(--color-shadow-grey-950)",
    "danger-50": "var(--color-red-50)",
    "danger-100": "var(--color-red-100)",
    "danger-200": "var(--color-red-200)",
    "danger-300": "var(--color-red-300)",
    "danger-400": "var(--color-red-400)",
    "danger-500": "var(--color-red-500)",
    "danger-600": "var(--color-red-600)",
    "danger-700": "var(--color-red-700)",
    "danger-800": "var(--color-red-800)",
    "danger-900": "var(--color-red-900)",
    "danger-950": "var(--color-red-950)",
    "warning-50": "var(--color-amber-50)",
    "warning-100": "var(--color-amber-100)",
    "warning-200": "var(--color-amber-200)",
    "warning-300": "var(--color-amber-300)",
    "warning-400": "var(--color-amber-400)",
    "warning-500": "var(--color-amber-500)",
    "warning-600": "var(--color-amber-600)",
    "warning-700": "var(--color-amber-700)",
    "warning-800": "var(--color-amber-800)",
    "warning-900": "var(--color-amber-900)",
    "warning-950": "var(--color-amber-950)",
    "info-50": "var(--color-sky-50)",
    "info-100": "var(--color-sky-100)",
    "info-200": "var(--color-sky-200)",
    "info-300": "var(--color-sky-300)",
    "info-400": "var(--color-sky-400)",
    "info-500": "var(--color-sky-500)",
    "info-600": "var(--color-sky-600)",
    "info-700": "var(--color-sky-700)",
    "info-800": "var(--color-sky-800)",
    "info-900": "var(--color-sky-900)",
    "info-950": "var(--color-sky-950)",
    "success-50": "var(--color-emerald-50)",
    "success-100": "var(--color-emerald-100)",
    "success-200": "var(--color-emerald-200)",
    "success-300": "var(--color-emerald-300)",
    "success-400": "var(--color-emerald-400)",
    "success-500": "var(--color-emerald-500)",
    "success-600": "var(--color-emerald-600)",
    "success-700": "var(--color-emerald-700)",
    "success-800": "var(--color-emerald-800)",
    "success-900": "var(--color-emerald-900)",
    "success-950": "var(--color-emerald-950)",
    "space-xs": "0.5rem",
    "space-sm": "0.625rem",
    "space-md": "0.75rem",
    "space-lg": "1rem",
    "space-xl": "1.25rem",
    "radius-xs": "0.125rem",
    "radius-sm": "0.375rem",
    "radius-md": "0.5rem",
    "radius-lg": "0.75rem",
    "radius-xl": "1rem",
    "size-xs": "2rem",
    "size-sm": "2.25rem",
    "size-md": "2.5rem",
    "size-lg": "2.75rem",
    "size-xl": "3rem",
    "gap-xs": "0.25rem",
    "gap-sm": "0.375rem",
    "gap-md": "0.5rem",
    "gap-lg": "0.625rem",
    "gap-xl": "0.75rem",
    "type-xs": "0.75rem",
    "type-sm": "0.875rem",
    "type-md": "1rem",
    "type-lg": "1.125rem",
    "type-xl": "1.25rem",
    "white": "#ffffff",
    "black": "#000000"
  },
  "semantics": {
    "bg-background": [
      "var(--{ns}-white)",
      "var(--{ns}-neutral-950)"
    ],
    "bg-surface": [
      "var(--{ns}-white)",
      "var(--{ns}-neutral-950)"
    ],
    "text-foreground": [
      "var(--{ns}-neutral-900)",
      "var(--{ns}-neutral-100)"
    ],
    "text-muted": [
      "var(--{ns}-neutral-500)",
      "var(--{ns}-neutral-400)"
    ],
    "border-default": [
      "var(--{ns}-neutral-100)",
      "var(--{ns}-neutral-800)"
    ],
    "text-placeholder": [
      "var(--{ns}-neutral-400)",
      "var(--{ns}-neutral-600)"
    ],
    "bg-brand": [
      "var(--{ns}-brand-500)",
      "var(--{ns}-brand-400)"
    ],
    "bg-brand-hover": [
      "var(--{ns}-brand-600)",
      "var(--{ns}-brand-300)"
    ],
    "text-brand": [
      "var(--{ns}-brand-600)",
      "var(--{ns}-brand-400)"
    ],
    "text-on-brand": [
      "var(--{ns}-neutral-50)",
      "var(--{ns}-neutral-950)"
    ],
    "bg-brand-soft": [
      "var(--{ns}-brand-50)",
      "color-mix(in oklab, var(--{ns}-brand-500) 16%, transparent)"
    ],
    "bg-brand-soft-hover": [
      "var(--{ns}-brand-100)",
      "color-mix(in oklab, var(--{ns}-brand-500) 26%, transparent)"
    ],
    "border-brand": [
      "var(--{ns}-brand-500)",
      "var(--{ns}-brand-400)"
    ],
    "border-brand-soft": "color-mix(in oklab, var(--{ns}-brand-500) 26%, transparent)",
    "ring-brand": "color-mix(in oklab, var(--{ns}-brand-500) 50%, transparent)",
    "bg-neutral": [
      "var(--{ns}-neutral-800)",
      "var(--{ns}-neutral-200)"
    ],
    "bg-neutral-hover": [
      "var(--{ns}-neutral-700)",
      "var(--{ns}-neutral-300)"
    ],
    "text-neutral": [
      "var(--{ns}-neutral-700)",
      "var(--{ns}-neutral-300)"
    ],
    "text-on-neutral": [
      "var(--{ns}-neutral-50)",
      "var(--{ns}-neutral-900)"
    ],
    "bg-neutral-soft": [
      "var(--{ns}-neutral-50)",
      "color-mix(in oklab, var(--{ns}-neutral-500) 16%, transparent)"
    ],
    "bg-neutral-soft-hover": [
      "var(--{ns}-neutral-100)",
      "color-mix(in oklab, var(--{ns}-neutral-500) 26%, transparent)"
    ],
    "border-neutral": [
      "var(--{ns}-neutral-200)",
      "var(--{ns}-neutral-700)"
    ],
    "ring-neutral": "color-mix(in oklab, var(--{ns}-neutral-500) 50%, transparent)",
    "bg-danger": [
      "var(--{ns}-danger-600)",
      "var(--{ns}-danger-400)"
    ],
    "bg-danger-hover": [
      "var(--{ns}-danger-700)",
      "var(--{ns}-danger-300)"
    ],
    "text-danger": [
      "var(--{ns}-danger-600)",
      "var(--{ns}-danger-400)"
    ],
    "text-on-danger": [
      "var(--{ns}-neutral-50)",
      "var(--{ns}-neutral-950)"
    ],
    "bg-danger-soft": [
      "var(--{ns}-danger-50)",
      "color-mix(in oklab, var(--{ns}-danger-500) 16%, transparent)"
    ],
    "bg-danger-soft-hover": [
      "var(--{ns}-danger-100)",
      "color-mix(in oklab, var(--{ns}-danger-500) 26%, transparent)"
    ],
    "border-danger": [
      "var(--{ns}-danger-500)",
      "var(--{ns}-danger-400)"
    ],
    "ring-danger": "color-mix(in oklab, var(--{ns}-danger-500) 50%, transparent)",
    "bg-warning": [
      "var(--{ns}-warning-500)",
      "var(--{ns}-warning-400)"
    ],
    "bg-warning-hover": [
      "var(--{ns}-warning-600)",
      "var(--{ns}-warning-300)"
    ],
    "text-warning": [
      "var(--{ns}-warning-700)",
      "var(--{ns}-warning-400)"
    ],
    "text-on-warning": [
      "var(--{ns}-neutral-950)",
      "var(--{ns}-neutral-950)"
    ],
    "bg-warning-soft": [
      "var(--{ns}-warning-50)",
      "color-mix(in oklab, var(--{ns}-warning-500) 16%, transparent)"
    ],
    "bg-warning-soft-hover": [
      "var(--{ns}-warning-100)",
      "color-mix(in oklab, var(--{ns}-warning-500) 26%, transparent)"
    ],
    "border-warning": [
      "var(--{ns}-warning-600)",
      "var(--{ns}-warning-400)"
    ],
    "ring-warning": "color-mix(in oklab, var(--{ns}-warning-500) 50%, transparent)",
    "bg-info": [
      "var(--{ns}-info-700)",
      "var(--{ns}-info-400)"
    ],
    "bg-info-hover": [
      "var(--{ns}-info-800)",
      "var(--{ns}-info-300)"
    ],
    "text-info": [
      "var(--{ns}-info-700)",
      "var(--{ns}-info-400)"
    ],
    "text-on-info": [
      "var(--{ns}-neutral-50)",
      "var(--{ns}-neutral-950)"
    ],
    "bg-info-soft": [
      "var(--{ns}-info-50)",
      "color-mix(in oklab, var(--{ns}-info-500) 16%, transparent)"
    ],
    "bg-info-soft-hover": [
      "var(--{ns}-info-100)",
      "color-mix(in oklab, var(--{ns}-info-500) 26%, transparent)"
    ],
    "border-info": [
      "var(--{ns}-info-600)",
      "var(--{ns}-info-400)"
    ],
    "ring-info": "color-mix(in oklab, var(--{ns}-info-500) 50%, transparent)",
    "bg-success": [
      "var(--{ns}-success-700)",
      "var(--{ns}-success-400)"
    ],
    "bg-success-hover": [
      "var(--{ns}-success-800)",
      "var(--{ns}-success-300)"
    ],
    "text-success": [
      "var(--{ns}-success-700)",
      "var(--{ns}-success-400)"
    ],
    "text-on-success": [
      "var(--{ns}-neutral-50)",
      "var(--{ns}-neutral-950)"
    ],
    "bg-success-soft": [
      "var(--{ns}-success-50)",
      "color-mix(in oklab, var(--{ns}-success-500) 16%, transparent)"
    ],
    "bg-success-soft-hover": [
      "var(--{ns}-success-100)",
      "color-mix(in oklab, var(--{ns}-success-500) 26%, transparent)"
    ],
    "border-success": [
      "var(--{ns}-success-600)",
      "var(--{ns}-success-400)"
    ],
    "ring-success": "color-mix(in oklab, var(--{ns}-success-500) 50%, transparent)"
  },
  "components": {
    "button": {
      "bg-primary-solid": "var(--{ns}-bg-brand)",
      "bg-primary-solid-hover": "var(--{ns}-bg-brand-hover)",
      "text-primary-solid": "var(--{ns}-text-on-brand)",
      "bg-primary-soft": "var(--{ns}-bg-brand-soft)",
      "bg-primary-soft-hover": "var(--{ns}-bg-brand-soft-hover)",
      "text-primary-outlined": "var(--{ns}-text-brand)",
      "border-primary-outlined": "var(--{ns}-border-brand)",
      "ring-primary": "var(--{ns}-switch-ring-brand)",
      "bg-neutral-solid": "var(--{ns}-bg-neutral)",
      "bg-neutral-solid-hover": "var(--{ns}-bg-neutral-hover)",
      "text-neutral-solid": "var(--{ns}-text-on-neutral)",
      "bg-neutral-soft": "var(--{ns}-tag-bg-neutral-soft)",
      "bg-neutral-soft-hover": "var(--{ns}-button-bg-neutral-soft-hover)",
      "text-neutral-outlined": "var(--{ns}-message-text-neutral)",
      "border-neutral-outlined": "var(--{ns}-message-border-neutral)",
      "ring-neutral": "var(--{ns}-button-ring-neutral)",
      "bg-danger-solid": "var(--{ns}-bg-danger)",
      "bg-danger-solid-hover": "var(--{ns}-bg-danger-hover)",
      "text-danger-solid": "var(--{ns}-text-on-danger)",
      "bg-danger-soft": "var(--{ns}-tag-bg-danger-soft)",
      "bg-danger-soft-hover": "var(--{ns}-button-bg-danger-soft-hover)",
      "text-danger-outlined": "var(--{ns}-message-text-danger)",
      "border-danger-outlined": "var(--{ns}-message-border-danger)",
      "ring-danger": "var(--{ns}-button-ring-danger)",
      "bg-warning-solid": "var(--{ns}-bg-warning)",
      "bg-warning-solid-hover": "var(--{ns}-bg-warning-hover)",
      "text-warning-solid": "var(--{ns}-text-on-warning)",
      "bg-warning-soft": "var(--{ns}-tag-bg-warning-soft)",
      "bg-warning-soft-hover": "var(--{ns}-button-bg-warning-soft-hover)",
      "text-warning-outlined": "var(--{ns}-message-text-warning)",
      "border-warning-outlined": "var(--{ns}-message-border-warning)",
      "ring-warning": "var(--{ns}-button-ring-warning)",
      "bg-info-solid": "var(--{ns}-bg-info)",
      "bg-info-solid-hover": "var(--{ns}-bg-info-hover)",
      "text-info-solid": "var(--{ns}-text-on-info)",
      "bg-info-soft": "var(--{ns}-tag-bg-info-soft)",
      "bg-info-soft-hover": "var(--{ns}-button-bg-info-soft-hover)",
      "text-info-outlined": "var(--{ns}-message-text-info)",
      "border-info-outlined": "var(--{ns}-message-border-info)",
      "ring-info": "var(--{ns}-button-ring-info)",
      "bg-success-solid": "var(--{ns}-bg-success)",
      "bg-success-solid-hover": "var(--{ns}-bg-success-hover)",
      "text-success-solid": "var(--{ns}-text-on-success)",
      "bg-success-soft": "var(--{ns}-tag-bg-success-soft)",
      "bg-success-soft-hover": "var(--{ns}-button-bg-success-soft-hover)",
      "text-success-outlined": "var(--{ns}-message-text-success)",
      "border-success-outlined": "var(--{ns}-message-border-success)",
      "ring-success": "var(--{ns}-button-ring-success)",
      "px-sm": "var(--{ns}-space-md)",
      "px-md": "var(--{ns}-space-lg)",
      "px-lg": "var(--{ns}-space-xl)",
      "h-sm": "var(--{ns}-size-sm)",
      "h-md": "var(--{ns}-size-md)",
      "h-lg": "var(--{ns}-size-lg)",
      "gap-sm": "var(--{ns}-gap-sm)",
      "gap-md": "var(--{ns}-gap-md)",
      "gap-lg": "var(--{ns}-gap-lg)",
      "text-sm": "var(--{ns}-type-sm)",
      "text-md": "var(--{ns}-type-sm)",
      "text-lg": "var(--{ns}-type-lg)",
      "rounded": "var(--{ns}-radius-md)"
    },
    "accordion": {
      "bg-item-outlined": "var(--{ns}-bg-background)",
      "bg-item-soft": "var(--{ns}-tag-bg-neutral-soft)",
      "border-item": "var(--{ns}-border-default)",
      "text-item": "var(--{ns}-text-foreground)",
      "text-value": "var(--{ns}-text-foreground)",
      "text-indicator": "var(--{ns}-breadcrumbs-text-muted)",
      "text-indicator-open": "var(--{ns}-text-foreground)",
      "ring-focus": "var(--{ns}-switch-ring-brand)",
      "gap": "0.5rem",
      "px-item": "var(--{ns}-space-lg)",
      "py-item": "var(--{ns}-space-md)",
      "pb-item": "var(--{ns}-space-md)",
      "gap-item": "var(--{ns}-gap-md)",
      "text-size-item": "var(--{ns}-type-sm)",
      "rounded-item": "var(--{ns}-radius-md)"
    },
    "avatar": {
      "size": "2.5em",
      "rounded-square": "var(--{ns}-radius-md)",
      "border": "color-mix(in oklab, currentColor 50%, transparent)",
      "bg-primary-soft": "var(--{ns}-bg-brand-soft)",
      "text-primary-soft": "var(--{ns}-text-brand)",
      "bg-primary-solid": "var(--{ns}-bg-brand)",
      "text-primary-solid": "var(--{ns}-text-on-brand)",
      "bg-neutral-soft": "var(--{ns}-tag-bg-neutral-soft)",
      "text-neutral-soft": "var(--{ns}-message-text-neutral)",
      "bg-neutral-solid": "var(--{ns}-bg-neutral)",
      "text-neutral-solid": "var(--{ns}-text-on-neutral)",
      "bg-danger-soft": "var(--{ns}-tag-bg-danger-soft)",
      "text-danger-soft": "var(--{ns}-message-text-danger)",
      "bg-danger-solid": "var(--{ns}-bg-danger)",
      "text-danger-solid": "var(--{ns}-text-on-danger)",
      "bg-warning-soft": "var(--{ns}-tag-bg-warning-soft)",
      "text-warning-soft": "var(--{ns}-message-text-warning)",
      "bg-warning-solid": "var(--{ns}-bg-warning)",
      "text-warning-solid": "var(--{ns}-text-on-warning)",
      "bg-info-soft": "var(--{ns}-tag-bg-info-soft)",
      "text-info-soft": "var(--{ns}-message-text-info)",
      "bg-info-solid": "var(--{ns}-bg-info)",
      "text-info-solid": "var(--{ns}-text-on-info)",
      "bg-success-soft": "var(--{ns}-tag-bg-success-soft)",
      "text-success-soft": "var(--{ns}-message-text-success)",
      "bg-success-solid": "var(--{ns}-bg-success)",
      "text-success-solid": "var(--{ns}-text-on-success)"
    },
    "breadcrumbs": {
      "gap": "0.5em",
      "text-icon": "0.875em",
      "text-muted": "var(--{ns}-breadcrumbs-text-muted)",
      "text-current": "var(--{ns}-text-foreground)"
    },
    "checkbox": {
      "bg-soft": "var(--{ns}-button-bg-neutral-soft-hover)",
      "bg-outlined": "var(--{ns}-bg-background)",
      "bg-checked": "var(--{ns}-bg-brand)",
      "border-outlined": "var(--{ns}-message-border-neutral)",
      "border-checked": "var(--{ns}-border-brand)",
      "border-invalid": "var(--{ns}-message-border-danger)",
      "ring-brand": "var(--{ns}-switch-ring-brand)",
      "rounded-sm": "0.25rem",
      "rounded-md": "0.375rem",
      "rounded-lg": "0.5rem",
      "size-sm": "1rem",
      "size-md": "1.25rem",
      "size-lg": "1.5rem"
    },
    "divider": {
      "border-primary": "var(--{ns}-border-brand)",
      "text-primary": "var(--{ns}-text-brand)",
      "border-neutral": "var(--{ns}-border-default)",
      "text-neutral": "var(--{ns}-breadcrumbs-text-muted)",
      "border-danger": "var(--{ns}-message-border-danger)",
      "text-danger": "var(--{ns}-message-text-danger)",
      "border-warning": "var(--{ns}-message-border-warning)",
      "text-warning": "var(--{ns}-message-text-warning)",
      "border-info": "var(--{ns}-message-border-info)",
      "text-info": "var(--{ns}-message-text-info)",
      "border-success": "var(--{ns}-message-border-success)",
      "text-success": "var(--{ns}-message-text-success)"
    },
    "group": {
      "bg-soft": "var(--{ns}-tag-bg-neutral-soft)",
      "bg-outlined": "var(--{ns}-bg-background)"
    },
    "input": {
      "bg-soft": "var(--{ns}-tag-bg-neutral-soft)",
      "bg-outlined": "var(--{ns}-bg-background)",
      "border-outlined": "var(--{ns}-message-border-neutral)",
      "border-focus": "var(--{ns}-border-brand)",
      "border-invalid": "var(--{ns}-message-border-danger)",
      "text-default": "var(--{ns}-text-foreground)",
      "text-placeholder": "var(--{ns}-textarea-text-placeholder)",
      "px-sm": "var(--{ns}-space-sm)",
      "px-md": "var(--{ns}-space-md)",
      "px-lg": "var(--{ns}-space-lg)",
      "h-sm": "var(--{ns}-size-sm)",
      "h-md": "var(--{ns}-size-md)",
      "h-lg": "var(--{ns}-size-lg)",
      "text-sm": "var(--{ns}-type-sm)",
      "text-md": "var(--{ns}-type-md)",
      "text-lg": "var(--{ns}-type-md)",
      "rounded": "var(--{ns}-radius-md)"
    },
    "listbox": {
      "text-default": "var(--{ns}-text-foreground)",
      "bg-soft": "var(--{ns}-tag-bg-neutral-soft)",
      "bg-outlined": "var(--{ns}-bg-background)",
      "border-outlined": "var(--{ns}-message-border-neutral)",
      "border-invalid": "var(--{ns}-message-border-danger)",
      "bg-item-hover": "var(--{ns}-tag-bg-neutral-soft)",
      "bg-item-selected": "var(--{ns}-tag-bg-neutral-soft)",
      "bg-item-soft-hover": "var(--{ns}-button-bg-neutral-soft-hover)",
      "bg-item-soft-selected": "var(--{ns}-button-bg-neutral-soft-hover)",
      "ring-item-highlighted": "var(--{ns}-switch-ring-brand)",
      "text-item-selected": "var(--{ns}-text-brand)",
      "px-sm": "var(--{ns}-space-sm)",
      "px-md": "var(--{ns}-space-md)",
      "px-lg": "var(--{ns}-space-lg)",
      "h-sm": "var(--{ns}-size-sm)",
      "h-md": "var(--{ns}-size-md)",
      "h-lg": "var(--{ns}-size-lg)",
      "gap-sm": "var(--{ns}-gap-sm)",
      "gap-md": "var(--{ns}-gap-md)",
      "gap-lg": "var(--{ns}-gap-lg)",
      "text-sm": "var(--{ns}-type-sm)",
      "text-md": "var(--{ns}-type-md)",
      "text-lg": "var(--{ns}-type-md)",
      "gap": "0.125rem",
      "p": "0.25rem",
      "rounded": "var(--{ns}-radius-md)",
      "rounded-item": "calc(var(--{ns}-radius-md) - 4px)"
    },
    "menu": {
      "text-default": "var(--{ns}-breadcrumbs-text-muted)",
      "text-heading": "var(--{ns}-breadcrumbs-text-muted)",
      "text-item": "var(--{ns}-breadcrumbs-text-muted)",
      "text-item-hover": "var(--{ns}-text-foreground)",
      "bg-item-hover": "var(--{ns}-tag-bg-neutral-soft)",
      "gap": "0.125rem",
      "py-heading": "0.25rem",
      "px-heading-sm": "var(--{ns}-space-sm)",
      "px-heading-md": "var(--{ns}-space-md)",
      "px-heading-lg": "var(--{ns}-space-lg)",
      "px-item-sm": "var(--{ns}-space-sm)",
      "px-item-md": "var(--{ns}-space-md)",
      "px-item-lg": "var(--{ns}-space-lg)",
      "gap-item-sm": "var(--{ns}-gap-sm)",
      "gap-item-md": "var(--{ns}-gap-md)",
      "gap-item-lg": "var(--{ns}-gap-lg)",
      "h-item-sm": "var(--{ns}-size-sm)",
      "h-item-md": "var(--{ns}-size-md)",
      "h-item-lg": "var(--{ns}-size-lg)",
      "rounded-item-sm": "var(--{ns}-radius-sm)",
      "rounded-item-md": "var(--{ns}-radius-md)",
      "rounded-item-lg": "var(--{ns}-radius-lg)",
      "text-sm": "var(--{ns}-type-sm)",
      "text-md": "var(--{ns}-type-sm)",
      "text-lg": "var(--{ns}-type-md)"
    },
    "message": {
      "bg-primary-soft": "var(--{ns}-bg-brand-soft)",
      "text-primary": "var(--{ns}-text-brand)",
      "border-primary": "var(--{ns}-border-brand)",
      "bg-neutral-soft": "var(--{ns}-tag-bg-neutral-soft)",
      "text-neutral": "var(--{ns}-message-text-neutral)",
      "border-neutral": "var(--{ns}-message-border-neutral)",
      "bg-danger-soft": "var(--{ns}-tag-bg-danger-soft)",
      "text-danger": "var(--{ns}-message-text-danger)",
      "border-danger": "var(--{ns}-message-border-danger)",
      "bg-warning-soft": "var(--{ns}-tag-bg-warning-soft)",
      "text-warning": "var(--{ns}-message-text-warning)",
      "border-warning": "var(--{ns}-message-border-warning)",
      "bg-info-soft": "var(--{ns}-tag-bg-info-soft)",
      "text-info": "var(--{ns}-message-text-info)",
      "border-info": "var(--{ns}-message-border-info)",
      "bg-success-soft": "var(--{ns}-tag-bg-success-soft)",
      "text-success": "var(--{ns}-message-text-success)",
      "border-success": "var(--{ns}-message-border-success)"
    },
    "radio": {
      "border-outlined": "var(--{ns}-message-border-neutral)",
      "bg-soft": "var(--{ns}-button-bg-neutral-soft-hover)",
      "bg-outlined": "var(--{ns}-bg-background)",
      "border-checked": "var(--{ns}-border-brand)",
      "bg-checked": "var(--{ns}-bg-brand)",
      "ring-brand": "var(--{ns}-switch-ring-brand)",
      "border-invalid": "var(--{ns}-message-border-danger)",
      "size-sm": "1rem",
      "size-md": "1.25rem",
      "size-lg": "1.5rem"
    },
    "scroll-area": {
      "w-scrollbar-y": "10px",
      "h-scrollbar-x": "10px",
      "w-thumb-y": "4px",
      "h-thumb-x": "4px",
      "size-thumb-y": "20px",
      "size-thumb-x": "20px",
      "translate-thumb-y": "0px",
      "translate-thumb-x": "0px",
      "rounded-thumb": "999px",
      "bg-thumb": "var(--{ns}-neutral-100)",
      "bg-thumb-hover": "var(--{ns}-neutral-200)"
    },
    "select-button": {
      "border-outlined": "var(--{ns}-message-border-neutral)",
      "bg-item-outlined": "var(--{ns}-button-bg-neutral-soft-hover)",
      "bg-soft": "var(--{ns}-tag-bg-neutral-soft)",
      "bg-outlined": "var(--{ns}-bg-background)",
      "bg-item-soft": "color-white",
      "text-default": "var(--{ns}-breadcrumbs-text-muted)",
      "text-selected": "var(--{ns}-text-foreground)",
      "px-sm": "var(--{ns}-space-sm)",
      "px-md": "var(--{ns}-space-md)",
      "px-lg": "var(--{ns}-space-lg)",
      "h-sm": "var(--{ns}-size-sm)",
      "h-md": "var(--{ns}-size-md)",
      "h-lg": "var(--{ns}-size-lg)",
      "gap-sm": "var(--{ns}-gap-sm)",
      "gap-md": "var(--{ns}-gap-md)",
      "gap-lg": "var(--{ns}-gap-lg)"
    },
    "select": {
      "text-default": "var(--{ns}-text-foreground)",
      "text-placeholder": "var(--{ns}-neutral-400)",
      "bg-soft": "var(--{ns}-neutral-100)",
      "bg-outlined": "var(--{ns}-bg-background)",
      "border-outlined": "var(--{ns}-neutral-300)",
      "border-underlined": "var(--{ns}-neutral-200)",
      "border-hover": "var(--{ns}-neutral-400)",
      "border-invalid": "color-mix(in oklab, var(--{ns}-danger-500) 50%, transparent)",
      "bg-popup": "color-white",
      "border-popup": "var(--{ns}-neutral-100)"
    },
    "switch": {
      "border": "var(--{ns}-message-border-neutral)",
      "border-checked": "var(--{ns}-border-brand)",
      "border-invalid": "var(--{ns}-message-border-danger)",
      "bg-soft": "var(--{ns}-button-bg-neutral-soft-hover)",
      "bg-outlined": "var(--{ns}-bg-background)",
      "bg-checked": "var(--{ns}-bg-brand)",
      "bg-thumb-outlined": "var(--{ns}-button-bg-neutral-soft-hover)",
      "bg-thumb-checked": "var(--{ns}-bg-brand)",
      "bg-thumb-soft": "color-white",
      "ring-brand": "var(--{ns}-switch-ring-brand)",
      "h": "1.5rem",
      "p": "0.125rem",
      "rounded": "9999px"
    },
    "table": {
      "px-cell": "0.75rem",
      "py-cell": "0.625rem",
      "px-head": "0.75rem",
      "py-head": "0.5rem",
      "top-sticky": "0px"
    },
    "tag": {
      "gap": "0.35em",
      "h": "1.75em",
      "px": "0.5em",
      "rounded": "0.5em",
      "border": "color-mix(in oklab, currentColor 30%, transparent)",
      "ps-avatar": "0.125rem",
      "ps-avatar-border": "1px",
      "pe-avatar": "0.125rem",
      "pe-avatar-border": "1px",
      "bg-primary-soft": "var(--{ns}-bg-brand-soft)",
      "text-primary-soft": "var(--{ns}-text-brand)",
      "bg-primary-solid": "var(--{ns}-bg-brand)",
      "text-primary-solid": "var(--{ns}-text-on-brand)",
      "bg-neutral-soft": "var(--{ns}-tag-bg-neutral-soft)",
      "text-neutral-soft": "var(--{ns}-message-text-neutral)",
      "bg-neutral-solid": "var(--{ns}-bg-neutral)",
      "text-neutral-solid": "var(--{ns}-text-on-neutral)",
      "bg-danger-soft": "var(--{ns}-tag-bg-danger-soft)",
      "text-danger-soft": "var(--{ns}-message-text-danger)",
      "bg-danger-solid": "var(--{ns}-bg-danger)",
      "text-danger-solid": "var(--{ns}-text-on-danger)",
      "bg-warning-soft": "var(--{ns}-tag-bg-warning-soft)",
      "text-warning-soft": "var(--{ns}-message-text-warning)",
      "bg-warning-solid": "var(--{ns}-bg-warning)",
      "text-warning-solid": "var(--{ns}-text-on-warning)",
      "bg-info-soft": "var(--{ns}-tag-bg-info-soft)",
      "text-info-soft": "var(--{ns}-message-text-info)",
      "bg-info-solid": "var(--{ns}-bg-info)",
      "text-info-solid": "var(--{ns}-text-on-info)",
      "bg-success-soft": "var(--{ns}-tag-bg-success-soft)",
      "text-success-soft": "var(--{ns}-message-text-success)",
      "bg-success-solid": "var(--{ns}-bg-success)",
      "text-success-solid": "var(--{ns}-text-on-success)"
    },
    "textarea": {
      "bg-soft": "var(--{ns}-tag-bg-neutral-soft)",
      "bg-outlined": "var(--{ns}-bg-background)",
      "border-outlined": "var(--{ns}-message-border-neutral)",
      "border-focus": "var(--{ns}-border-brand)",
      "border-invalid": "var(--{ns}-message-border-danger)",
      "text-default": "var(--{ns}-text-foreground)",
      "text-placeholder": "var(--{ns}-textarea-text-placeholder)",
      "px-sm": "var(--{ns}-space-sm)",
      "px-md": "var(--{ns}-space-md)",
      "px-lg": "var(--{ns}-space-lg)",
      "text-sm": "var(--{ns}-type-sm)",
      "text-md": "var(--{ns}-type-md)",
      "text-lg": "var(--{ns}-type-md)",
      "rounded": "var(--{ns}-radius-md)"
    }
  }
} as const
export { tokens as default }
