import { defineCommand } from 'citty'
import { mkdir, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { loadTheme, watchTask } from './utils'
import type { Part } from '../types'
import type { Theme } from '../theme.ts'
import type { ThemeFiles } from '../render'
import { renderUtilities } from '../render/utilities'
import { compileComponentRules } from '../compile'

export async function buildTokens(name: string, theme: Theme, outDir: string, part?: Part): Promise<void> {
  const runtimeDir = path.join(outDir, name)

  await rm(runtimeDir, { recursive: true, force: true })
  await mkdir(runtimeDir, { recursive: true })

  const parts = parsePartList(part)
  const shouldGenerateTokens = parts.some((p) => p === 'tokens')
  const shouldGenerateTemplates = parts.some((p) => p.startsWith('templates'))

  if (shouldGenerateTokens) {
    const selectedComponents = parseSelectedComponents(parts, 'templates')
    await compileTemplates(theme, runtimeDir, selectedComponents)
    await writeTokensFile(theme, runtimeDir)
  } else if (shouldGenerateTemplates) {
    const selectedComponents = parseSelectedComponents(parts, 'templates')
    await compileTemplates(theme, runtimeDir, selectedComponents)
  }

  const relative = path.relative(process.cwd(), runtimeDir)
  console.log(`tokens -> ${relative}`)
}

function parseSelectedComponents(parts: Part[], prefix: string): string[] {
  return parts
    .filter((p) => p.startsWith(`${prefix}:`))
    .flatMap((p) =>
      p
        .split(':')[1]
        .split(',')
        .map((c) => c.trim())
        .filter(Boolean),
    )
}

function filterComponents(allComponents: ThemeFiles['components'], selected: string[]): ThemeFiles['components'] {
  if (selected.length === 0) return allComponents
  return Object.fromEntries(Object.entries(allComponents).filter(([ui]) => selected.includes(ui)))
}

async function compileTemplates(theme: Theme, runtimeDir: string, selectedComponents: string[]): Promise<void> {
  const files = theme.toFiles()
  const ns = theme.namespace ?? 'd'
  const allUtilities = renderUtilities(theme.registry)
  const buildRoot = path.join(process.cwd(), '.build', `theme-${Date.now()}`)
  await mkdir(buildRoot, { recursive: true })
  await writeFile(path.join(buildRoot, 'utilities.css'), allUtilities)

  try {
    const components = filterComponents(files.components, selectedComponents)

    for (const [ui, file] of Object.entries(components)) {
      const { template, hasContent } = await compileComponentRules(file.rules, {
        namespace: ns,
        utilitiesCss: allUtilities,
        from: path.join(buildRoot, `${ui}-rules.css`),
      })

      if (!hasContent) continue

      await writeFile(
        path.join(runtimeDir, `${ui}.ts`),
        [
          `/* generated by @dotdev/theme — do not edit */`,
          `var template = ${JSON.stringify(template)}`,
          `export { template }`,
          ``,
        ].join('\n'),
      )
    }
  } finally {
    await rm(buildRoot, { recursive: true, force: true })
  }
}

async function writeTokensFile(theme: Theme, runtimeDir: string): Promise<void> {
  await writeFile(
    path.join(runtimeDir, 'tokens.ts'),
    [
      `// generated by @dotdev/theme — do not edit`,
      `var tokens = ${JSON.stringify(theme.toTokens(), null, 2)} as const`,
      `export { tokens as default }`,
      ``,
    ].join('\n'),
  )
}

function parsePartList(part?: Part): Part[] {
  if (!part) return ['tokens', 'templates']
  return part.split(',').map((p) => p.trim()) as Part[]
}

export const tokens = defineCommand({
  meta: {
    name: 'tokens',
    description: 'Generate runtime TypeScript tokens and component templates',
  },
  args: {
    input: {
      type: 'string',
      description: 'Path to theme config file',
      required: true,
    },
    output: {
      type: 'string',
      description: 'Output directory',
      default: './dist',
    },
    name: {
      type: 'string',
      description: 'Theme name',
      default: 'default',
    },
    part: {
      type: 'string',
      description: 'Parts to generate: tokens, templates, templates:ui1,ui2 (default: all)',
    },
    watch: {
      type: 'boolean',
      description: 'Watch for changes and rebuild',
      default: false,
    },
    'watch-path': {
      type: 'string',
      description: 'Directory or file to watch (default: input file)',
    },
  },
  async run({ args }) {
    const input = path.resolve(args.input)
    const watchPath = args['watch-path'] ? path.resolve(args['watch-path']) : input

    async function build(): Promise<void> {
      const theme = await loadTheme(input)
      const output = path.resolve(args.output)

      await buildTokens(args.name, theme, output, args.part as Part)
    }

    await build()

    if (args.watch) {
      watchTask(build, watchPath)
    }
  },
})
