import { defineCommand } from 'citty'
import { mkdir, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import postcss from 'postcss'
import chokidar from 'chokidar'
import { collectLocals, compile, inlineVars, loadTheme, pruneEmptyRules, stripBanner } from './utils'
import type { Theme } from '../theme.ts'
import { renderUtilities } from '../render/utilities'
import { toComponentTemplate } from '../runtime/toTemplate'

const entry = '@import "tailwindcss/utilities" source(none);'
const reference = ['@reference "tailwindcss";', '@reference "./.build/utilities.css";'].join('\n')

async function buildTokens(name: string, theme: Theme, outDir: string): Promise<void> {
  const runtimeDir = path.join(outDir, name)
  await mkdir(runtimeDir, { recursive: true })

  const files = theme.toFiles()
  const ns = theme.namespace ?? 'd'

  const allUtilities = renderUtilities(theme.registry)

  for (const [ui, file] of Object.entries(files.components)) {
    const buildDir = path.join(outDir, 'components', ui, '.build')
    await mkdir(buildDir, { recursive: true })
    await writeFile(path.join(buildDir, 'utilities.css'), allUtilities)

    const rules = await compile(
      [entry, reference, file.rules].join('\n'),
      path.join(outDir, 'components', ui, 'rules.css'),
    )

    const stripped = stripBanner(rules)
    if (!stripped.trim()) {
      await rm(buildDir, { recursive: true })
      continue
    }

    const ast = postcss.parse(stripped)

    const propertyValues = new Map<string, string>()
    for (const node of ast.nodes ?? []) {
      if (node.type === 'atrule' && node.name === 'property') {
        let initial: string | undefined
        node.walkDecls((decl) => {
          if (decl.prop === 'initial-value') initial = decl.value
        })
        if (initial != null) propertyValues.set(node.params.trim(), initial)
      }
    }

    for (const node of ast.nodes ?? []) {
      if (node.type !== 'rule') continue
      const locals = collectLocals(node)
      const resolve = (name: string, fallback: string | undefined): string | undefined => {
        if (name.startsWith(`--${ns}-`)) return undefined
        const local = locals.get(name)
        if (local != null) return local
        const prop = propertyValues.get(name)
        if (prop != null) return prop
        if (fallback != null) return fallback
        return undefined
      }
      const dead: postcss.Declaration[] = []
      node.walkDecls((decl) => {
        if (decl.prop.startsWith('--tw-')) {
          dead.push(decl)
          return
        }
        decl.value = inlineVars(decl.value, resolve)
      })
      for (const decl of dead) decl.remove()
    }

    pruneEmptyRules(ast)

    const componentNodes: string[] = []
    for (const node of ast.nodes ?? []) {
      const isPropertiesLayer = node.type === 'atrule' && node.name === 'layer' && node.params.trim() === 'properties'
      if (node.type === 'atrule' && node.name === 'property') continue
      if (isPropertiesLayer) continue
      componentNodes.push(node.toString())
    }

    const template = toComponentTemplate(componentNodes.join('\n'), ns)
    await writeFile(
      path.join(runtimeDir, `${ui}.ts`),
      [
        `/* generated by @dotdev/theme — do not edit */`,
        `var template = ${JSON.stringify(template)}`,
        `export { template }`,
        ``,
      ].join('\n'),
    )

    await rm(buildDir, { recursive: true })
  }

  await writeFile(
    path.join(runtimeDir, 'tokens.ts'),
    [
      `// generated by @dotdev/theme — do not edit`,
      `var tokens = ${JSON.stringify(theme.toTokens(), null, 2)} as const`,
      `export { tokens as default }`,
      ``,
    ].join('\n'),
  )
}

export const tokens = defineCommand({
  meta: {
    name: 'tokens',
    description: 'Generate runtime TypeScript tokens and component templates',
  },
  args: {
    input: {
      type: 'string',
      description: 'Path to theme config file',
      required: true,
    },
    output: {
      type: 'string',
      description: 'Output directory',
      default: './dist',
    },
    name: {
      type: 'string',
      description: 'Theme name',
      default: 'default',
    },
    watch: {
      type: 'boolean',
      description: 'Watch for changes and rebuild',
      default: false,
    },
    'watch-path': {
      type: 'string',
      description: 'Directory or file to watch (default: input file)',
    },
  },
  async run({ args }) {
    const input = path.resolve(args.input)
    const watchPath = args['watch-path'] ? path.resolve(args['watch-path']) : input

    async function build(): Promise<void> {
      const theme = await loadTheme(input)
      const output = path.resolve(args.output)

      await buildTokens(args.name, theme, output)

      const relative = path.relative(process.cwd(), path.join(output, args.name))
      console.log(`tokens -> ${relative}`)
    }

    await build()

    if (args.watch) {
      console.log(`Watching ${watchPath} for changes...`)
      chokidar.watch(watchPath, { ignoreInitial: true }).on('change', async () => {
        console.log('Change detected, rebuilding...')
        await build()
      })
    }
  },
})
