import { defineComponent } from '@dotdev/design'

export const button = defineComponent({
  ui: 'button',
  semantics: {
    'bg-primary-solid': 'bg-brand',
    'bg-primary-solid-hover': 'bg-brand-hover',
    'text-primary-solid': 'text-on-brand',
    'bg-primary-soft': 'bg-brand-soft',
    'bg-primary-soft-hover': 'bg-brand-soft-hover',
    'text-primary-outlined': 'text-brand',
    'border-primary-outlined': 'border-brand',
    'ring-primary': 'ring-brand',

    'bg-neutral-solid': 'bg-neutral',
    'bg-neutral-solid-hover': 'bg-neutral-hover',
    'text-neutral-solid': 'text-on-neutral',
    'bg-neutral-soft': 'bg-neutral-soft',
    'bg-neutral-soft-hover': 'bg-neutral-soft-hover',
    'text-neutral-outlined': 'text-neutral',
    'border-neutral-outlined': 'border-neutral',
    'ring-neutral': 'ring-neutral',

    'bg-danger-solid': 'bg-danger',
    'bg-danger-solid-hover': 'bg-danger-hover',
    'text-danger-solid': 'text-on-danger',
    'bg-danger-soft': 'bg-danger-soft',
    'bg-danger-soft-hover': 'bg-danger-soft-hover',
    'text-danger-outlined': 'text-danger',
    'border-danger-outlined': 'border-danger',
    'ring-danger': 'ring-danger',

    'bg-warning-solid': 'bg-warning',
    'bg-warning-solid-hover': 'bg-warning-hover',
    'text-warning-solid': 'text-on-warning',
    'bg-warning-soft': 'bg-warning-soft',
    'bg-warning-soft-hover': 'bg-warning-soft-hover',
    'text-warning-outlined': 'text-warning',
    'border-warning-outlined': 'border-warning',
    'ring-warning': 'ring-warning',

    'bg-info-solid': 'bg-info',
    'bg-info-solid-hover': 'bg-info-hover',
    'text-info-solid': 'text-on-info',
    'bg-info-soft': 'bg-info-soft',
    'bg-info-soft-hover': 'bg-info-soft-hover',
    'text-info-outlined': 'text-info',
    'border-info-outlined': 'border-info',
    'ring-info': 'ring-info',

    'bg-success-solid': 'bg-success',
    'bg-success-solid-hover': 'bg-success-hover',
    'text-success-solid': 'text-on-success',
    'bg-success-soft': 'bg-success-soft',
    'bg-success-soft-hover': 'bg-success-soft-hover',
    'text-success-outlined': 'text-success',
    'border-success-outlined': 'border-success',
    'ring-success': 'ring-success',

    'px-sm': 'space-md',
    'px-md': 'space-lg',
    'px-lg': 'space-xl',
    'h-sm': 'size-sm',
    'h-md': 'size-md',
    'h-lg': 'size-lg',
    'gap-sm': 'gap-sm',
    'gap-md': 'gap-md',
    'gap-lg': 'gap-lg',
    'type-sm': 'type-sm',
    'type-md': 'type-sm',
    'type-lg': 'type-lg',
    rounded: 'radius-md',
  },

  utilities: {
    'size-sm': `button-type-sm button-h-sm button-px-sm button-gap-sm`,
    'size-md': `button-type-md button-h-md button-px-md button-gap-md`,
    'size-lg': `button-type-lg button-h-lg button-px-lg button-gap-lg`,
    transition: 'transition-[background-color,color,opacity,border-color]',
  },

  rules: {
    '&': `button-rounded outline-none inline-flex items-center justify-center font-semibold button-transition cursor-pointer`,
    '&--sm': `button-size-sm`,
    '&--md': `button-size-md`,
    '&--lg': `button-size-lg`,

    '&--solid': `shadow-[inset_0_1px_0_0_rgba(255,255,255,0.15)]`,
    '&--outlined': `border`,
    '&:is(&--outlined, &--ghost, &--text)': `bg-transparent`,

    '&--disabled': `disabled`,
    '&:not(:disabled):focus-visible': `ring-2`,

    '&--loading &__icon': `animate-spin`,
    '&__icon': `text-[1.2em]`,

    '&--primary.&--solid': `button-bg-primary-solid hover:button-bg-primary-solid-hover button-text-primary-solid`,
    '&--primary.&--soft': `button-bg-primary-soft hover:button-bg-primary-soft-hover`,
    '&--primary:is(&--outlined)': `button-border-primary-outlined`,
    '&--primary:is(&--outlined, &--ghost)': `hover:button-bg-primary-soft`,
    '&--primary:is(&--outlined, &--ghost, &--soft, &--text)': `button-text-primary-outlined`,
    '&--primary:focus-visible': `button-ring-primary`,

    '&--neutral.&--solid': `button-bg-neutral-solid hover:button-bg-neutral-solid-hover button-text-neutral-solid`,
    '&--neutral.&--soft': `button-bg-neutral-soft hover:button-bg-neutral-soft-hover`,
    '&--neutral:is(&--outlined)': `button-border-neutral-outlined`,
    '&--neutral:is(&--outlined, &--ghost)': `hover:button-bg-neutral-soft`,
    '&--neutral:is(&--outlined, &--ghost, &--soft, &--text)': `button-text-neutral-outlined`,
    '&--neutral:focus-visible': `button-ring-neutral`,

    '&--danger.&--solid': `button-bg-danger-solid hover:button-bg-danger-solid-hover button-text-danger-solid`,
    '&--danger.&--soft': `button-bg-danger-soft hover:button-bg-danger-soft-hover`,
    '&--danger:is(&--outlined)': `button-border-danger-outlined`,
    '&--danger:is(&--outlined, &--ghost)': `hover:button-bg-danger-soft`,
    '&--danger:is(&--outlined, &--ghost, &--soft, &--text)': `button-text-danger-outlined`,
    '&--danger:focus-visible': `button-ring-danger`,

    '&--warning.&--solid': `button-bg-warning-solid hover:button-bg-warning-solid-hover button-text-warning-solid`,
    '&--warning.&--soft': `button-bg-warning-soft hover:button-bg-warning-soft-hover`,
    '&--warning:is(&--outlined)': `button-border-warning-outlined`,
    '&--warning:is(&--outlined, &--ghost)': `hover:button-bg-warning-soft`,
    '&--warning:is(&--outlined, &--ghost, &--soft, &--text)': `button-text-warning-outlined`,
    '&--warning:focus-visible': `button-ring-warning`,

    '&--info.&--solid': `button-bg-info-solid hover:button-bg-info-solid-hover button-text-info-solid`,
    '&--info.&--soft': `button-bg-info-soft hover:button-bg-info-soft-hover`,
    '&--info:is(&--outlined)': `button-border-info-outlined`,
    '&--info:is(&--outlined, &--ghost)': `hover:button-bg-info-soft`,
    '&--info:is(&--outlined, &--ghost, &--soft, &--text)': `button-text-info-outlined`,
    '&--info:focus-visible': `button-ring-info`,

    '&--success.&--solid': `button-bg-success-solid hover:button-bg-success-solid-hover button-text-success-solid`,
    '&--success.&--soft': `button-bg-success-soft hover:button-bg-success-soft-hover`,
    '&--success:is(&--outlined)': `button-border-success-outlined`,
    '&--success:is(&--outlined, &--ghost)': `hover:button-bg-success-soft`,
    '&--success:is(&--outlined, &--ghost, &--soft, &--text)': `button-text-success-outlined`,
    '&--success:focus-visible': `button-ring-success`,
  },
})
