import type { Component } from 'vue'
import { createUiKit, defineUiKitConfig } from '@dotdev/ui-kit'

/* Icon map generated by the @dotdev/icons Vite plugin */
const icons: Record<string, Component> = {}

const base = defineUiKitConfig({ namespace: 'd', icons })

const landing = defineUiKitConfig({
  namespace: 'landing',
  icons,
  theme: {
    primitives: {/* …own brand ramp and scale… */},
    semantics: {/* …re-mapped tokens… */},
  },
})

export const uiKit = createUiKit([base, landing])
