import type { Component } from 'vue'
import { createUiKit } from '@dotdev/ui-kit'

/* Icon map generated by the @dotdev/icons Vite plugin */
const icons: Record<string, Component> = {}

export const uiKit = createUiKit({ namespace: 'd', icons })
