/* generated by @dotdev/theme — do not edit */
var template = "@layer components {\n  .{ns}-icon {\n    width: 1em;\n    height: 1em;\n  }\n  .{ns}-icon svg {\n    width: 1em;\n    height: 1em;\n  }\n}"
export { template }
