<script lang="ts" setup>
import { ref } from 'vue'
import { Button, Icon, Input, Switch, Tag } from '@dotdev/ui-kit'

definePage({ name: 'Dashboard', meta: { landing: true } })

const demoSwitch = ref(true)

const features = [
  {
    title: 'BEM + Tailwind',
    desc: 'Methodology and utilities that compose instead of fighting. Styles ship as CSS tokens and Tailwind utilities — no CSS-in-JS runtime.',
  },
  {
    title: 'Namespace theming',
    desc: 'Run several design systems in one app. Roll out the new look incrementally, while the old one keeps working.',
  },
  {
    title: 'Live documentation',
    desc: 'Every component ships with runnable examples, source and theme previews — generated by the studio docs framework.',
  },
]

const packages = [
  {
    name: 'ui-kit',
    icon: 'component-1',
    desc: 'Vue 3 components with BEM classes and three fills per control — soft, outlined, solid.',
  },
  {
    name: 'icons',
    icon: 'image',
    desc: 'An SVG icon set wired through the Vite plugin, ready to register with any namespace.',
  },
  {
    name: 'theme',
    icon: 'color-wheel',
    desc: 'CSS tokens and a defineSheet DSL: oklch palettes, a dark twin, per-namespace themes.',
  },
  {
    name: 'studio',
    icon: 'card-stack',
    desc: 'The docs framework: live examples, playgrounds and DocPage generated from component folders.',
  },
] as const

const steps = [
  {
    title: 'Register a namespace',
    desc: 'Wire the kit into your app once — pick a namespace and bundle the icon set.',
    code: `import { createUiKit } from '@dotdev/ui-kit'
import { icons } from '@dotdev/icons'

export const uiKit = createUiKit({
  namespace: 'd',
  icons,
})`,
  },
  {
    title: 'Tune components globally',
    desc: 'Override defaults for every instance — sizes, colors, variants — in one place.',
    code: `createUiKit({
  components: {
    button: { color: 'primary', variant: 'soft' },
    input: { size: 'md' },
  },
})`,
  },
  {
    title: 'Add a second design system',
    desc: 'Create another namespace for a new section and adopt it step by step, without touching the old look.',
    code: `export const appKit = createUiKit({
  namespace: 'app',
})`,
  },
]
</script>

<template>
  <main class="landing">
    <section class="landing__hero">
      <div class="landing__hero-copy">
        <p class="landing__kicker">
          <span class="landing__kicker-mark" />
          Dotdev — the precision workbench
        </p>

        <h1 class="landing__title">
          Vue 3 components,
          <span class="text-muted">built to spec.</span>
        </h1>

        <p class="landing__subtitle">
          A clean, deeply themeable UI kit. BEM + Tailwind with no CSS-in-JS, namespaced themes that coexist
          in one project, and every component documented with live examples.
        </p>

        <div class="landing__actions">
          <Button href="/ui-kit" size="lg">Browse components</Button>
          <Button href="/documentation/config" size="lg" variant="outlined">Get started</Button>
        </div>

        <p class="landing__meta">
          v0.1.0
          <span class="landing__meta-sep" />
          Open source
          <span class="landing__meta-sep" />
          4 packages
        </p>
      </div>

      <div class="landing__demo">
        <div class="landing__demo-bar">
          <span class="landing__demo-label">workbench · live</span>
          <span class="landing__demo-version">v0.1.0</span>
        </div>

        <div class="landing__demo-stage">
          <div class="landing__demo-row">
            <Input class="w-64" placeholder="Search components…" size="md" variant="soft" />
          </div>

          <div class="landing__demo-row">
            <Switch v-model="demoSwitch" />
            <Tag color="primary" label="Namespace" />
            <Tag label="BEM" variant="outlined" />
          </div>

          <div class="landing__demo-row">
            <Button label="Adopt" variant="soft" />
            <Button label="Outlined" variant="outlined" />
          </div>
        </div>
      </div>
    </section>

    <section class="landing__section">
      <div class="landing__section-head">
        <p class="landing__kicker">
          <span class="landing__kicker-mark" />
          Why
        </p>
        <h2 class="landing__section-title">Built like a workbench</h2>
        <p class="landing__section-sub">
          Small, visible surfaces with a single source of truth — no runtime, no magic, no lock-in.
        </p>
      </div>

      <div class="landing__features">
        <article v-for="(feature, index) in features" :key="feature.title" class="landing__feature">
          <p class="landing__feature-index">0{{ index + 1 }}</p>
          <h3 class="landing__feature-title">{{ feature.title }}</h3>
          <p class="landing__feature-desc">{{ feature.desc }}</p>
        </article>
      </div>
    </section>

    <section class="landing__section">
      <div class="landing__section-head">
        <p class="landing__kicker">
          <span class="landing__kicker-mark" />
          Stack
        </p>
        <h2 class="landing__section-title">Four packages, one system</h2>
        <p class="landing__section-sub">
          Everything ships together, but each package stays independent — install what you need.
        </p>
      </div>

      <div class="landing__packages">
        <article v-for="pkg in packages" :key="pkg.name" class="landing__package">
          <div class="landing__package-head">
            <span class="landing__package-icon">
              <Icon :name="pkg.icon" />
            </span>
            <span class="landing__package-name">{{ pkg.name }}</span>
          </div>
          <p class="landing__package-desc">{{ pkg.desc }}</p>
        </article>
      </div>
    </section>

    <section class="landing__section">
      <div class="landing__section-head">
        <p class="landing__kicker">
          <span class="landing__kicker-mark" />
          Start
        </p>
        <h2 class="landing__section-title">From zero to your first namespace</h2>
        <p class="landing__section-sub">
          No scaffolding to learn, no generator to run — three small steps and components are yours.
        </p>
      </div>

      <div class="landing__steps">
        <article v-for="(step, index) in steps" :key="step.title" class="landing__step">
          <p class="landing__step-index">0{{ index + 1 }}</p>
          <h3 class="landing__step-title">{{ step.title }}</h3>
          <p class="landing__step-desc">{{ step.desc }}</p>
          <pre class="landing__step-code">{{ step.code }}</pre>
        </article>
      </div>
    </section>

    <section class="landing__cta">
      <h2 class="landing__cta-title">Start building on the workbench.</h2>
      <p class="landing__cta-sub">
        Pick a component, open the source, and make it yours. Everything is themeable, nothing is locked in.
      </p>

      <div class="landing__cta-actions">
        <Button href="/ui-kit" size="lg">Browse components</Button>
        <Button href="/documentation/config" size="lg" variant="outlined">Read the docs</Button>
      </div>

      <p class="landing__cta-version">dotdev v0.1.0 — the precision workbench</p>
    </section>
  </main>
</template>
