import { defineConfig } from './src/builder/index.ts'

const sizeKeys = ['h', 'size']
const spaceKeys = ['px', 'py', 'p', 'pl', 'pr', 'pt', 'pb']

function flatMapObject<TKey extends PropertyKey, TValue>(
  keys: readonly TKey[],
  callback: (key: TKey) => Record<string, TValue>,
): Record<string, TValue> {
  return Object.assign({}, ...keys.map(callback))
}

export default defineConfig({
  name: 'Default',
  primitives: {
    'brand-50': 'var(--color-indigo-50)',
    'brand-100': 'var(--color-indigo-100)',
    'brand-200': 'var(--color-indigo-200)',
    'brand-300': 'var(--color-indigo-300)',
    'brand-400': 'var(--color-indigo-400)',
    'brand-500': 'var(--color-indigo-500)',
    'brand-600': 'var(--color-indigo-600)',
    'brand-700': 'var(--color-indigo-700)',
    'brand-800': 'var(--color-indigo-800)',
    'brand-900': 'var(--color-indigo-900)',
    'brand-950': 'var(--color-indigo-950)',

    'neutral-50': 'var(--color-shadow-grey-50)',
    'neutral-100': 'var(--color-shadow-grey-100)',
    'neutral-200': 'var(--color-shadow-grey-200)',
    'neutral-300': 'var(--color-shadow-grey-300)',
    'neutral-400': 'var(--color-shadow-grey-400)',
    'neutral-500': 'var(--color-shadow-grey-500)',
    'neutral-600': 'var(--color-shadow-grey-600)',
    'neutral-700': 'var(--color-shadow-grey-700)',
    'neutral-800': 'var(--color-shadow-grey-800)',
    'neutral-900': 'var(--color-shadow-grey-900)',
    'neutral-950': 'var(--color-shadow-grey-950)',

    'danger-50': 'var(--color-red-50)',
    'danger-100': 'var(--color-red-100)',
    'danger-200': 'var(--color-red-200)',
    'danger-300': 'var(--color-red-300)',
    'danger-400': 'var(--color-red-400)',
    'danger-500': 'var(--color-red-500)',
    'danger-600': 'var(--color-red-600)',
    'danger-700': 'var(--color-red-700)',
    'danger-800': 'var(--color-red-800)',
    'danger-900': 'var(--color-red-900)',
    'danger-950': 'var(--color-red-950)',

    'warning-50': 'var(--color-amber-50)',
    'warning-100': 'var(--color-amber-100)',
    'warning-200': 'var(--color-amber-200)',
    'warning-300': 'var(--color-amber-300)',
    'warning-400': 'var(--color-amber-400)',
    'warning-500': 'var(--color-amber-500)',
    'warning-600': 'var(--color-amber-600)',
    'warning-700': 'var(--color-amber-700)',
    'warning-800': 'var(--color-amber-800)',
    'warning-900': 'var(--color-amber-900)',
    'warning-950': 'var(--color-amber-950)',

    'info-50': 'var(--color-sky-50)',
    'info-100': 'var(--color-sky-100)',
    'info-200': 'var(--color-sky-200)',
    'info-300': 'var(--color-sky-300)',
    'info-400': 'var(--color-sky-400)',
    'info-500': 'var(--color-sky-500)',
    'info-600': 'var(--color-sky-600)',
    'info-700': 'var(--color-sky-700)',
    'info-800': 'var(--color-sky-800)',
    'info-900': 'var(--color-sky-900)',
    'info-950': 'var(--color-sky-950)',

    'success-50': 'var(--color-emerald-50)',
    'success-100': 'var(--color-emerald-100)',
    'success-200': 'var(--color-emerald-200)',
    'success-300': 'var(--color-emerald-300)',
    'success-400': 'var(--color-emerald-400)',
    'success-500': 'var(--color-emerald-500)',
    'success-600': 'var(--color-emerald-600)',
    'success-700': 'var(--color-emerald-700)',
    'success-800': 'var(--color-emerald-800)',
    'success-900': 'var(--color-emerald-900)',
    'success-950': 'var(--color-emerald-950)',

    'space-xs': '0.5rem',
    'space-sm': '0.625rem',
    'space-md': '0.75rem',
    'space-lg': '1rem',
    'space-xl': '1.25rem',

    'radius-xs': '0.125rem',
    'radius-sm': '0.375rem',
    'radius-md': '0.5rem',
    'radius-lg': '0.75rem',
    'radius-xl': '1rem',

    'size-xs': '2rem',
    'size-sm': '2.25rem',
    'size-md': '2.5rem',
    'size-lg': '2.75rem',
    'size-xl': '3rem',

    'gap-xs': '0.25rem',
    'gap-sm': '0.375rem',
    'gap-md': '0.5rem',
    'gap-lg': '0.625rem',
    'gap-xl': '0.75rem',

    'type-xs': '0.75rem',
    'type-sm': '0.875rem',
    'type-md': '1rem',
    'type-lg': '1.125rem',
    'type-xl': '1.25rem',

    white: '#ffffff',
    black: '#000000',
  },

  semantics: {
    text: '12px',
    'bg-background': ['white', 'neutral-950'],
    'bg-surface': ['white', 'neutral-950'],
    'text-foreground': ['neutral-900', 'neutral-100'],
    'text-muted': ['neutral-500', 'neutral-400'],
    'border-default': ['neutral-100', 'neutral-800'],
    'text-placeholder': ['neutral-400', 'neutral-600'],

    'bg-brand': ['brand-500', 'brand-400'],
    'bg-brand-hover': ['brand-600', 'brand-300'],
    'text-brand': ['brand-600', 'brand-400'],
    'text-on-brand': ['neutral-50', 'neutral-950'],
    'bg-brand-soft': ['brand-50', 'brand-500/16'],
    'bg-brand-soft-hover': ['brand-100', 'brand-500/26'],
    'border-brand': ['brand-500', 'brand-400'],
    'border-brand-soft': 'brand-500/26',
    'ring-brand': 'brand-500/50',

    'bg-neutral': ['neutral-800', 'neutral-200'],
    'bg-neutral-hover': ['neutral-700', 'neutral-300'],
    'text-neutral': ['neutral-700', 'neutral-300'],
    'text-on-neutral': ['neutral-50', 'neutral-900'],
    'bg-neutral-soft': ['neutral-50', 'neutral-500/16'],
    'bg-neutral-soft-hover': ['neutral-100', 'neutral-500/26'],
    'border-neutral': ['neutral-200', 'neutral-700'],
    'ring-neutral': 'neutral-500/50',

    'bg-danger': ['danger-600', 'danger-400'],
    'bg-danger-hover': ['danger-700', 'danger-300'],
    'text-danger': ['danger-600', 'danger-400'],
    'text-on-danger': ['neutral-50', 'neutral-950'],
    'bg-danger-soft': ['danger-50', 'danger-500/16'],
    'bg-danger-soft-hover': ['danger-100', 'danger-500/26'],
    'border-danger': ['danger-500', 'danger-400'],
    'ring-danger': 'danger-500/50',

    'bg-warning': ['warning-500', 'warning-400'],
    'bg-warning-hover': ['warning-600', 'warning-300'],
    'text-warning': ['warning-700', 'warning-400'],
    'text-on-warning': ['neutral-950', 'neutral-950'],
    'bg-warning-soft': ['warning-50', 'warning-500/16'],
    'bg-warning-soft-hover': ['warning-100', 'warning-500/26'],
    'border-warning': ['warning-600', 'warning-400'],
    'ring-warning': 'warning-500/50',

    'bg-info': ['info-700', 'info-400'],
    'bg-info-hover': ['info-800', 'info-300'],
    'text-info': ['info-700', 'info-400'],
    'text-on-info': ['neutral-50', 'neutral-950'],
    'bg-info-soft': ['info-50', 'info-500/16'],
    'bg-info-soft-hover': ['info-100', 'info-500/26'],
    'border-info': ['info-600', 'info-400'],
    'ring-info': 'info-500/50',

    'bg-success': ['success-700', 'success-400'],
    'bg-success-hover': ['success-800', 'success-300'],
    'text-success': ['success-700', 'success-400'],
    'text-on-success': ['neutral-50', 'neutral-950'],
    'bg-success-soft': ['success-50', 'success-500/16'],
    'bg-success-soft-hover': ['success-100', 'success-500/26'],
    'border-success': ['success-600', 'success-400'],
    'ring-success': 'success-500/50',
  },

  utilities: {
    ...flatMapObject(sizeKeys, (key) => ({
      [`${key}-xs`]: `${key}-(--$ns-size-xs)`,
      [`${key}-sm`]: `${key}-(--$ns-size-sm)`,
      [`${key}-md`]: `${key}-(--$ns-size-md)`,
      [`${key}-lg`]: `${key}-(--$ns-size-lg)`,
      [`${key}-xl`]: `${key}-(--$ns-size-xl)`,
    })),

    ...flatMapObject(spaceKeys, (key) => ({
      [`${key}-xs`]: `${key}-(--$ns-space-xs)`,
      [`${key}-sm`]: `${key}-(--$ns-space-sm)`,
      [`${key}-md`]: `${key}-(--$ns-space-md)`,
      [`${key}-lg`]: `${key}-(--$ns-space-lg)`,
      [`${key}-xl`]: `${key}-(--$ns-space-xl)`,
    })),

    'gap-xs': 'gap-(--$ns-gap-xs)',
    'gap-sm': 'gap-(--$ns-gap-sm)',
    'gap-md': 'gap-(--$ns-gap-md)',
    'gap-lg': 'gap-(--$ns-gap-lg)',
    'gap-xl': 'gap-(--$ns-gap-xl)',

    'type-xs': 'text-(length:--$ns-type-xs)',
    'type-sm': 'text-(length:--$ns-type-sm)',
    'type-md': 'text-(length:--$ns-type-md)',
    'type-lg': 'text-(length:--$ns-type-lg)',
    'type-xl': 'text-(length:--$ns-type-xl)',

    'radius-xs': 'rounded-(--$ns-radius-xs)',
    'radius-sm': 'rounded-(--$ns-radius-sm)',
    'radius-md': 'rounded-(--$ns-radius-md)',
    'radius-lg': 'rounded-(--$ns-radius-lg)',
    'radius-xl': 'rounded-(--$ns-radius-xl)',

    disabled: 'pointer-events-none opacity-60',
  },

  components: {
    accordion: {
      config: {
        ui: 'accordion',

        semantics: {
          'bg-item-outlined': 'bg-background',
          'bg-item-soft': 'bg-neutral-soft',
          'border-item': 'border-default',

          'text-item': 'text-foreground',
          'text-value': 'text-foreground',
          'text-indicator': 'text-muted',
          'text-indicator-open': 'text-foreground',
          'ring-focus': 'ring-brand',
          gap: '0.5rem',

          'px-item': 'space-lg',
          'py-item': 'space-md',
          'pb-item': 'space-md',
          'gap-item': 'gap-md',
          'text-size-item': 'type-sm',
          'rounded-item': 'radius-md',
        },

        utilities: {
          transition: 'transition-[background-color,color,border-color,opacity]',
          'transition-indicator': 'transition-[transform,rotate,color]',
          'transition-panel': 'transition-[height] duration-200',
        },

        rules: {
          '&': 'flex w-full flex-col accordion-transition',
          '&--outlined': 'accordion-gap',
          '&--soft': 'accordion-gap',
          '&--disabled': 'disabled',

          '&__item': 'flex flex-col rounded-[inherit]',
          '&--outlined &__item': 'accordion-rounded-item border accordion-border-item accordion-bg-item-outlined',
          '&--soft &__item': 'accordion-rounded-item accordion-bg-item-soft',
          '&--underline &__item': 'border-b accordion-border-item last:border-b-0',

          '&__trigger': 'rounded-[inherit] flex w-full items-center accordion-gap-item accordion-px-item accordion-py-item accordion-text-size-item accordion-text-item text-left font-medium outline-none cursor-pointer select-none accordion-transition',
          '&__trigger:focus-visible': 'ring-2 accordion-ring-focus',
          '&__trigger:disabled': 'disabled',

          '&__label': 'truncate',

          '&__indicator': 'ml-auto accordion-text-indicator accordion-transition-indicator',
          '&__trigger--open &__indicator': 'rotate-180 accordion-text-indicator-open',

          '&__panel': 'accordion-transition-panel overflow-hidden',
          '&__value': 'block accordion-px-item accordion-pb-item accordion-text-size-item accordion-text-value',
        },
      },
    },

    button: {
      config: {
        ui: 'button',

        semantics: {
          'bg-primary-solid': 'bg-brand',
          'bg-primary-solid-hover': 'bg-brand-hover',
          'text-primary-solid': 'text-on-brand',
          'bg-primary-soft': 'bg-brand-soft',
          'bg-primary-soft-hover': 'bg-brand-soft-hover',
          'text-primary-outlined': 'text-brand',
          'border-primary-outlined': 'border-brand',
          'ring-primary': 'ring-brand',

          'bg-neutral-solid': 'bg-neutral',
          'bg-neutral-solid-hover': 'bg-neutral-hover',
          'text-neutral-solid': 'text-on-neutral',
          'bg-neutral-soft': 'bg-neutral-soft',
          'bg-neutral-soft-hover': 'bg-neutral-soft-hover',
          'text-neutral-outlined': 'text-neutral',
          'border-neutral-outlined': 'border-neutral',
          'ring-neutral': 'ring-neutral',

          'bg-danger-solid': 'bg-danger',
          'bg-danger-solid-hover': 'bg-danger-hover',
          'text-danger-solid': 'text-on-danger',
          'bg-danger-soft': 'bg-danger-soft',
          'bg-danger-soft-hover': 'bg-danger-soft-hover',
          'text-danger-outlined': 'text-danger',
          'border-danger-outlined': 'border-danger',
          'ring-danger': 'ring-danger',

          'bg-warning-solid': 'bg-warning',
          'bg-warning-solid-hover': 'bg-warning-hover',
          'text-warning-solid': 'text-on-warning',
          'bg-warning-soft': 'bg-warning-soft',
          'bg-warning-soft-hover': 'bg-warning-soft-hover',
          'text-warning-outlined': 'text-warning',
          'border-warning-outlined': 'border-warning',
          'ring-warning': 'ring-warning',

          'bg-info-solid': 'bg-info',
          'bg-info-solid-hover': 'bg-info-hover',
          'text-info-solid': 'text-on-info',
          'bg-info-soft': 'bg-info-soft',
          'bg-info-soft-hover': 'bg-info-soft-hover',
          'text-info-outlined': 'text-info',
          'border-info-outlined': 'border-info',
          'ring-info': 'ring-info',

          'bg-success-solid': 'bg-success',
          'bg-success-solid-hover': 'bg-success-hover',
          'text-success-solid': 'text-on-success',
          'bg-success-soft': 'bg-success-soft',
          'bg-success-soft-hover': 'bg-success-soft-hover',
          'text-success-outlined': 'text-success',
          'border-success-outlined': 'border-success',
          'ring-success': 'ring-success',

          'px-sm': 'space-md',
          'px-md': 'space-lg',
          'px-lg': 'space-xl',
          'h-sm': 'size-sm',
          'h-md': 'size-md',
          'h-lg': 'size-lg',
          'gap-sm': 'gap-sm',
          'gap-md': 'gap-md',
          'gap-lg': 'gap-lg',
          'text-sm': 'type-sm',
          'text-md': 'type-sm',
          'text-lg': 'type-lg',
          rounded: 'radius-md',
        },

        utilities: {
          'size-sm': 'button-text-sm button-h-sm button-px-sm button-gap-sm',
          'size-md': 'button-text-md button-h-md button-px-md button-gap-md',
          'size-lg': 'button-text-lg button-h-lg button-px-lg button-gap-lg',
          transition: 'transition-[background-color,color,opacity,border-color]',
        },

        rules: {
          '&': 'button-rounded outline-none inline-flex items-center justify-center font-semibold button-transition cursor-pointer',
          '&--sm': 'button-size-sm',
          '&--md': 'button-size-md',
          '&--lg': 'button-size-lg',

          '&--solid': 'shadow-[inset_0_1px_0_0_rgba(255,255,255,0.15)]',
          '&--outlined': 'border',
          '&:is(&--outlined, &--ghost, &--text)': 'bg-transparent',

          '&--disabled': 'disabled',
          '&:not(:disabled):focus-visible': 'ring-2',

          '&--loading &__icon': 'animate-spin',
          '&__icon': 'text-[1.2em]',

          '&--primary.&--solid': 'button-bg-primary-solid hover:button-bg-primary-solid-hover button-text-primary-solid',
          '&--primary.&--soft': 'button-bg-primary-soft hover:button-bg-primary-soft-hover',
          '&--primary:is(&--outlined)': 'button-border-primary-outlined',
          '&--primary:is(&--outlined, &--ghost)': 'hover:button-bg-primary-soft',
          '&--primary:is(&--outlined, &--ghost, &--soft, &--text)': 'button-text-primary-outlined',
          '&--primary:focus-visible': 'button-ring-primary',

          '&--neutral.&--solid': 'button-bg-neutral-solid hover:button-bg-neutral-solid-hover button-text-neutral-solid',
          '&--neutral.&--soft': 'button-bg-neutral-soft hover:button-bg-neutral-soft-hover',
          '&--neutral:is(&--outlined)': 'button-border-neutral-outlined',
          '&--neutral:is(&--outlined, &--ghost)': 'hover:button-bg-neutral-soft',
          '&--neutral:is(&--outlined, &--ghost, &--soft, &--text)': 'button-text-neutral-outlined',
          '&--neutral:focus-visible': 'button-ring-neutral',

          '&--danger.&--solid': 'button-bg-danger-solid hover:button-bg-danger-solid-hover button-text-danger-solid',
          '&--danger.&--soft': 'button-bg-danger-soft hover:button-bg-danger-soft-hover',
          '&--danger:is(&--outlined)': 'button-border-danger-outlined',
          '&--danger:is(&--outlined, &--ghost)': 'hover:button-bg-danger-soft',
          '&--danger:is(&--outlined, &--ghost, &--soft, &--text)': 'button-text-danger-outlined',
          '&--danger:focus-visible': 'button-ring-danger',

          '&--warning.&--solid': 'button-bg-warning-solid hover:button-bg-warning-solid-hover button-text-warning-solid',
          '&--warning.&--soft': 'button-bg-warning-soft hover:button-bg-warning-soft-hover',
          '&--warning:is(&--outlined)': 'button-border-warning-outlined',
          '&--warning:is(&--outlined, &--ghost)': 'hover:button-bg-warning-soft',
          '&--warning:is(&--outlined, &--ghost, &--soft, &--text)': 'button-text-warning-outlined',
          '&--warning:focus-visible': 'button-ring-warning',

          '&--info.&--solid': 'button-bg-info-solid hover:button-bg-info-solid-hover button-text-info-solid',
          '&--info.&--soft': 'button-bg-info-soft hover:button:bg-info-soft-hover',
          '&--info:is(&--outlined)': 'button-border-info-outlined',
          '&--info:is(&--outlined, &--ghost)': 'hover:button-bg-info-soft',
          '&--info:is(&--outlined, &--ghost, &--soft, &--text)': 'button-text-info-outlined',
          '&--info:focus-visible': 'button-ring-info',

          '&--success.&--solid': 'button-bg-success-solid hover:button-bg-success-solid-hover button-text-success-solid',
          '&--success.&--soft': 'button-bg-success-soft hover:button-bg-success-soft-hover',
          '&--success:is(&--outlined)': 'button-border-success-outlined',
          '&--success:is(&--outlined, &--ghost)': 'hover:button-bg-success-soft',
          '&--success:is(&--outlined, &--ghost, &--soft, &--text)': 'button-text-success-outlined',
          '&--success:focus-visible': 'button-ring-success',
        },
      },
    },
  },
})
